import type { AstroEvent } from './types';

/** Etkinlik demo verisi — ana sayfa kartlarındaki slug'larla eşleşir. */
export const events: AstroEvent[] = [
  {
    slug: 'perseid-2026',
    title: 'Perseid Meteor Yağmuru Gözlem Kampı',
    type: 'meteor-yagmuru',
    city: 'Antalya',
    venue: 'Saklıkent Gözlem Alanı',
    coords: { latitude: 36.7817, longitude: 30.3494 },
    startsAt: '2026-08-12T18:00:00+03:00',
    endsAt: '2026-08-13T06:00:00+03:00',
    free: false,
    camping: true,
    kidsFriendly: true,
    astrophotoFocused: true,
    telescopesProvided: true,
    capacity: 120,
    registered: 84,
    organizer: { name: 'Antalya Astronomi Derneği', verified: true },
    description:
      'Yılın en zengin meteor yağmurunu Bortle 3 gökyüzü altında izliyoruz. Zirve gecesi saatte 100+ meteor bekleniyor; çadır alanı, teleskop istasyonları ve astrofoto köşesi hazır olacak.',
    program: [
      { time: '18:00', title: 'Kamp kurulumu ve karşılama' },
      { time: '20:30', title: 'Perseidler nereden gelir?', speaker: 'Dr. A. Kaya' },
      { time: '22:00', title: 'Çıplak gözle gözlem ve sayım pratiği' },
      { time: '00:30', title: 'Teleskoplarla gezegen turu (Satürn, Jüpiter)' },
      { time: '04:30', title: 'Zirve saati toplu gözlem' },
    ],
    observedTargets: ['Perseid meteorları', 'Satürn', 'Jüpiter', 'Samanyolu'],
    rules: [
      'Beyaz ışık kullanımı 21:00 sonrası yasaktır; kırmızı fener getirin.',
      'Çadır alanı araçlara kapalıdır, otopark 200 m mesafededir.',
    ],
    gradient: 'linear-gradient(135deg, #1e293b, #4c1d95)',
    source: { name: 'Organizatör bildirimi', lastVerifiedAt: '2026-07-10' },
  },
  {
    slug: 'karanlik-gokyuzu',
    title: 'Karanlık Gökyüzü Astrofotoğraf Atölyesi',
    type: 'astrofoto-kampi',
    city: 'Erzurum',
    venue: 'Palandöken Yaylası',
    coords: { latitude: 39.8508, longitude: 41.2417 },
    startsAt: '2026-08-20T16:00:00+03:00',
    endsAt: '2026-08-22T10:00:00+03:00',
    free: false,
    camping: true,
    kidsFriendly: false,
    astrophotoFocused: true,
    telescopesProvided: false,
    capacity: 30,
    registered: 27,
    organizer: { name: 'DeepSky Türkiye', verified: true },
    description:
      'İki gecelik uygulamalı atölye: kurulum, polar alignment, guiding, SHO veri toplama ve sabah oturumlarında işleme. Kendi ekipmanınızla katılım esastır; SQM 21.9 gökyüzü.',
    program: [
      { time: '1. Gün 16:00', title: 'Kurulum ve backfocus kontrolü' },
      { time: '1. Gün 21:00', title: 'Gece çekimi: Ha hedefleri' },
      { time: '2. Gün 10:00', title: 'WBPP ile kalibrasyon', speaker: 'D. Arslan' },
      { time: '2. Gün 21:00', title: 'Gece çekimi: OIII/SII' },
    ],
    observedTargets: ['NGC 7000', 'IC 1396', 'Sadr bölgesi'],
    gradient: 'linear-gradient(135deg, #0f172a, #7f1d1d)',
    source: { name: 'Organizatör bildirimi', lastVerifiedAt: '2026-07-08' },
  },
  {
    slug: 'halk-gozlemi',
    title: 'Halka Açık Teleskop Gözlemi',
    type: 'halk-gozlemi',
    city: 'İstanbul',
    venue: 'Maltepe Sahil Parkı',
    coords: { latitude: 41.0082, longitude: 28.9784 },
    startsAt: '2026-08-28T20:00:00+03:00',
    free: true,
    camping: false,
    kidsFriendly: true,
    astrophotoFocused: false,
    telescopesProvided: true,
    organizer: { name: 'İstanbul Gökyüzü Gönüllüleri', verified: false },
    description:
      'Şehir merkezinde herkese açık gözlem akşamı. 6 teleskopla Ay kraterleri, Satürn halkaları ve çift yıldızlar. Kayıt gerekmez, çocuklar için kısa anlatım köşesi bulunur.',
    program: [
      { time: '20:00', title: 'Kurulum ve Ay gözlemi' },
      { time: '21:30', title: 'Satürn ve Jüpiter' },
      { time: '22:30', title: 'Çift yıldızlar ve kapanış' },
    ],
    observedTargets: ['Ay', 'Satürn', 'Jüpiter', 'Albireo'],
    gradient: 'linear-gradient(135deg, #1e3a5f, #334155)',
    source: { name: 'Kullanıcı önerisi + editör onayı', lastVerifiedAt: '2026-07-12' },
  },
  {
    slug: 'gunes-gozlemi-izmir',
    title: 'H-alfa ile Güneş Gözlemi',
    type: 'gunes-gozlemi',
    city: 'İzmir',
    venue: 'Kültürpark',
    coords: { latitude: 38.4237, longitude: 27.1428 },
    startsAt: '2026-09-06T11:00:00+03:00',
    free: true,
    camping: false,
    kidsFriendly: true,
    astrophotoFocused: false,
    telescopesProvided: true,
    organizer: { name: 'Ege Üniversitesi Astronomi Kulübü', verified: true },
    description:
      'Özel H-alfa teleskoplarıyla güneş lekeleri ve protuberansları güvenle gözlemliyoruz. Güneşe asla çıplak gözle veya filtresiz teleskopla bakılmaz; tüm ekipman kulüp tarafından sağlanır.',
    program: [
      { time: '11:00', title: 'Güneş güvenliği anlatımı' },
      { time: '11:30', title: 'H-alfa ve beyaz ışık gözlemi' },
    ],
    observedTargets: ['Güneş lekeleri', 'Protuberanslar'],
    gradient: 'linear-gradient(135deg, #7c2d12, #b45309)',
    source: { name: 'Kulüp duyurusu', lastVerifiedAt: '2026-07-01' },
  },
  {
    slug: 'astronomi-101-webinar',
    title: 'Astronomiye Giriş: Ekipman Seçimi Webinarı',
    type: 'webinar',
    city: 'Online',
    venue: 'Canlı yayın',
    startsAt: '2026-07-30T21:00:00+03:00',
    free: true,
    camping: false,
    kidsFriendly: false,
    astrophotoFocused: true,
    telescopesProvided: false,
    organizer: { name: 'Astrohub Eğitim', verified: true },
    description:
      'İlk teleskop ve ilk astrofoto setup\'ı seçerken en sık yapılan hatalar; bütçe senaryolarıyla montür-öncelikli yaklaşım.',
    program: [{ time: '21:00', title: 'Sunum + soru/cevap', speaker: 'C. Demir' }],
    observedTargets: [],
    gradient: 'linear-gradient(135deg, #172554, #0e7490)',
    source: { name: 'Organizatör bildirimi', lastVerifiedAt: '2026-07-14' },
  },
  /*
   * Takvim ve harita görünümü için genişletilmiş tohum verisi.
   *
   * Beş kayıtla takvim ayları boş görünüyordu ve harita tek bir noktaya
   * düşüyordu — görünümlerin çalıştığını göstermek için değil, doğru
   * çalıştığını görebilmek için yeterli veri gerekiyor. Kayıtlar gerçek
   * mekânlara ve gerçek gök olaylarına (Orionid, Geminid, tutulmalar)
   * dayanır; organizatör adları örnektir ve `source` alanı bunu bildirir.
   */
  {
    slug: 'orionid-kapadokya',
    title: 'Orionid Meteor Gecesi — Kapadokya',
    type: 'meteor-yagmuru',
    city: 'Nevşehir',
    venue: 'Uçhisar Gözlem Terası',
    coords: { latitude: 38.6304, longitude: 34.8056 },
    startsAt: '2026-10-21T20:00:00+03:00',
    endsAt: '2026-10-22T05:00:00+03:00',
    free: false,
    camping: true,
    kidsFriendly: true,
    astrophotoFocused: true,
    telescopesProvided: true,
    capacity: 80,
    registered: 41,
    organizer: { name: 'Kapadokya Gökbilim Topluluğu', verified: true },
    description:
      'Halley kuyruklu yıldızının artıklarından doğan Orionidler, peribacalarının üzerinde. Zirve gecesi saatte 20–25 meteor bekleniyor; ay bu yıl zirveyi bozmuyor.',
    program: [
      { time: '20:00', title: 'Karşılama ve alan kurulumu' },
      { time: '21:30', title: 'Meteor yağmuru nasıl sayılır?', speaker: 'E. Yıldırım' },
      { time: '23:00', title: 'Geniş açı astrofoto istasyonu' },
      { time: '02:00', title: 'Zirve gözlemi' },
    ],
    observedTargets: ['Orionid meteorları', 'Orion Bulutsusu', 'Jüpiter'],
    rules: ['Beyaz ışık yasak; kırmızı fener zorunlu.', 'Alan rüzgârlıdır, kışlık giyinin.'],
    gradient: 'linear-gradient(135deg, #1f2937, #4338ca)',
    source: { name: 'Organizatör bildirimi', lastVerifiedAt: '2026-07-20' },
  },
  {
    slug: 'geminid-2026-erciyes',
    title: 'Geminid Meteor Yağmuru Kampı',
    type: 'meteor-yagmuru',
    city: 'Kayseri',
    venue: 'Erciyes Yaylası',
    coords: { latitude: 38.5333, longitude: 35.45 },
    startsAt: '2026-12-13T18:00:00+03:00',
    endsAt: '2026-12-14T06:00:00+03:00',
    free: false,
    camping: true,
    kidsFriendly: false,
    astrophotoFocused: true,
    telescopesProvided: false,
    capacity: 60,
    registered: 22,
    organizer: { name: 'Erciyes Astronomi Kulübü', verified: true },
    description:
      'Yılın en yoğun meteor yağmuru, 2000 m rakımda ve kuru kış havasında. Geminidler yavaş ve parlak; geniş açı çekim için en verimli gece.',
    program: [
      { time: '18:00', title: 'Kamp kurulumu, sıcak içecek' },
      { time: '20:00', title: 'Kışın astrofotoğraf: pil, çiy, odak kayması' },
      { time: '22:00', title: 'Gözlem ve sayım' },
    ],
    observedTargets: ['Geminid meteorları', 'Orion', 'Kış Üçgeni'],
    rules: ['Gece −15°C görülebilir; kışlık uyku tulumu zorunlu.'],
    gradient: 'linear-gradient(135deg, #0f172a, #1e3a8a)',
    source: { name: 'Organizatör bildirimi', lastVerifiedAt: '2026-07-18' },
  },
  {
    slug: 'tubitak-ulusal-gozlemevi-ziyaret',
    title: 'TUG Ulusal Gözlemevi Halka Açık Ziyaret Günü',
    type: 'halk-gozlemi',
    city: 'Antalya',
    venue: 'Bakırlıtepe — TÜBİTAK Ulusal Gözlemevi',
    coords: { latitude: 36.8247, longitude: 30.3353 },
    startsAt: '2026-09-19T14:00:00+03:00',
    endsAt: '2026-09-19T23:00:00+03:00',
    free: true,
    camping: false,
    kidsFriendly: true,
    astrophotoFocused: false,
    telescopesProvided: true,
    capacity: 120,
    registered: 118,
    organizer: { name: 'Ulusal Gözlemevi Tanıtım Ekibi', verified: true },
    description:
      'Türkiye\'nin en büyük optik teleskoplarının bulunduğu 2500 m rakımlı tepede rehberli tur ve akşam gözlemi. Kontenjan sınırlıdır, kayıt zorunludur.',
    program: [
      { time: '14:00', title: 'Kubbe turu ve teleskop tanıtımı' },
      { time: '17:30', title: 'Gün batımı ve güneş gözlemi' },
      { time: '20:00', title: 'Gece gözlemi: Satürn, M13, M57' },
    ],
    observedTargets: ['Satürn', 'M 13', 'M 57', 'Ay'],
    rules: ['Yola özel araçla çıkış izne tabidir; ring servisi kullanılır.'],
    gradient: 'linear-gradient(135deg, #292524, #78716c)',
    source: { name: 'Kurum duyurusu', lastVerifiedAt: '2026-07-22' },
  },
  {
    slug: 'ankara-astrofoto-atolyesi',
    title: 'Görüntü İşleme Atölyesi: Kalibrasyon ve Yığınlama',
    type: 'atolye',
    city: 'Ankara',
    venue: 'ODTÜ Kültür ve Kongre Merkezi',
    coords: { latitude: 39.8917, longitude: 32.7833 },
    startsAt: '2026-09-05T10:00:00+03:00',
    endsAt: '2026-09-05T17:00:00+03:00',
    free: false,
    camping: false,
    kidsFriendly: false,
    astrophotoFocused: true,
    telescopesProvided: false,
    capacity: 40,
    registered: 31,
    organizer: { name: 'Ankara Astrofotoğraf Grubu', verified: true },
    description:
      'Dark, flat ve bias\'ın ne işe yaradığını gerçek veriyle adım adım işliyoruz. Katılımcılar kendi ham kayıtlarını getirebilir; Siril ve PixInsight akışları paralel gösterilir.',
    program: [
      { time: '10:00', title: 'Kalibrasyon kareleri: neden ve nasıl' },
      { time: '13:00', title: 'Yığınlama ve hizalama' },
      { time: '15:00', title: 'Streç, gürültü, renk kalibrasyonu' },
    ],
    observedTargets: [],
    rules: ['Dizüstü bilgisayar getirmek gerekir.'],
    gradient: 'linear-gradient(135deg, #1e1b4b, #6d28d9)',
    source: { name: 'Organizatör bildirimi', lastVerifiedAt: '2026-07-15' },
  },
  {
    slug: 'bursa-uludag-gozlem-senligi',
    title: 'Uludağ Gözlem Şenliği',
    type: 'gozlem-senligi',
    city: 'Bursa',
    venue: 'Uludağ Sarıalan Mevkii',
    coords: { latitude: 40.0994, longitude: 29.1608 },
    startsAt: '2026-08-29T17:00:00+03:00',
    endsAt: '2026-08-30T07:00:00+03:00',
    free: true,
    camping: true,
    kidsFriendly: true,
    astrophotoFocused: false,
    telescopesProvided: true,
    capacity: 200,
    registered: 96,
    organizer: { name: 'Bursa Astronomi Derneği', verified: true },
    description:
      'Marmara\'nın en erişilebilir karanlık noktasında toplu gözlem. Yirmiye yakın teleskop kurulur; ekipmanı olmayanlar sıraya girerek gözlem yapabilir.',
    program: [
      { time: '17:00', title: 'Alan açılışı' },
      { time: '19:30', title: 'Gökyüzü turu (lazer işaretli)' },
      { time: '21:00', title: 'Teleskop istasyonları' },
    ],
    observedTargets: ['Satürn', 'M 31', 'M 13', 'Albireo'],
    rules: ['Araç farları alan içinde kapalı; park girişte.'],
    gradient: 'linear-gradient(135deg, #14532d, #166534)',
    source: { name: 'Dernek duyurusu', lastVerifiedAt: '2026-07-19' },
  },
  {
    slug: 'van-karanlik-gokyuzu-kampi',
    title: 'Van Gölü Karanlık Gökyüzü Kampı',
    type: 'astrofoto-kampi',
    city: 'Van',
    venue: 'Gevaş Sahil Kamp Alanı',
    coords: { latitude: 38.2947, longitude: 43.1053 },
    startsAt: '2026-10-09T16:00:00+03:00',
    endsAt: '2026-10-11T10:00:00+03:00',
    free: false,
    camping: true,
    kidsFriendly: false,
    astrophotoFocused: true,
    telescopesProvided: false,
    capacity: 35,
    registered: 12,
    organizer: { name: 'Doğu Anadolu Gökyüzü İnisiyatifi', verified: false },
    description:
      'Bortle 2–3 gökyüzü altında iki gecelik çekim kampı. Göl yüzeyi ufku açtığı için düşük deklinasyonlu hedefler bu sahada erişilebilir.',
    program: [
      { time: '16:00', title: 'Kamp kurulumu ve kutupsal hizalama' },
      { time: '21:00', title: 'Hedef seçimi ve kadraj planlama' },
      { time: '01:00', title: 'Gece yarısı hedef değişimi' },
    ],
    observedTargets: ['Samanyolu merkezi', 'NGC 7000', 'M 33'],
    rules: ['Jeneratör yasak; taşınabilir güç istasyonu kullanın.'],
    gradient: 'linear-gradient(135deg, #082f49, #0369a1)',
    source: { name: 'Organizatör bildirimi', lastVerifiedAt: '2026-07-21' },
  },
  {
    slug: 'izmir-cocuk-gokyuzu-atolyesi',
    title: 'Çocuklar İçin Gökyüzü Atölyesi',
    type: 'cocuk-aile',
    city: 'İzmir',
    venue: 'İzmir Bilim Merkezi',
    coords: { latitude: 38.4622, longitude: 27.2167 },
    startsAt: '2026-08-08T13:00:00+03:00',
    endsAt: '2026-08-08T16:00:00+03:00',
    free: true,
    camping: false,
    kidsFriendly: true,
    astrophotoFocused: false,
    telescopesProvided: true,
    capacity: 50,
    registered: 50,
    organizer: { name: 'İzmir Bilim Merkezi', verified: true },
    description:
      '7–12 yaş grubuna yönelik atölye: takımyıldız kartı yapımı, ay yüzeyi maketi ve güvenli güneş gözlemi. Veli katılımı serbesttir.',
    program: [
      { time: '13:00', title: 'Takımyıldız kartı atölyesi' },
      { time: '14:30', title: 'Güvenli güneş gözlemi' },
    ],
    observedTargets: ['Güneş'],
    gradient: 'linear-gradient(135deg, #7c2d12, #ea580c)',
    source: { name: 'Kurum duyurusu', lastVerifiedAt: '2026-07-12' },
  },
  {
    slug: 'trabzon-planetaryum-gecesi',
    title: 'Planetaryum Gecesi: Kış Gökyüzü',
    type: 'planetaryum',
    city: 'Trabzon',
    venue: 'Trabzon Bilim Merkezi Planetaryumu',
    coords: { latitude: 41.0027, longitude: 39.7168 },
    startsAt: '2026-11-14T19:00:00+03:00',
    endsAt: '2026-11-14T21:30:00+03:00',
    free: false,
    camping: false,
    kidsFriendly: true,
    astrophotoFocused: false,
    telescopesProvided: false,
    capacity: 90,
    registered: 44,
    organizer: { name: 'Trabzon Bilim Merkezi', verified: true },
    description:
      'Kubbe altında kış gökyüzü turu ve ardından hava açıksa terasta teleskop gözlemi. Karadeniz\'de kapalı hava riski yüksek olduğu için program kubbe odaklı kurgulandı.',
    program: [
      { time: '19:00', title: 'Kubbe gösterimi: Kış Üçgeni' },
      { time: '20:30', title: 'Teras gözlemi (hava uygunsa)' },
    ],
    observedTargets: ['Orion Bulutsusu', 'Pleiades'],
    gradient: 'linear-gradient(135deg, #172554, #1d4ed8)',
    source: { name: 'Kurum duyurusu', lastVerifiedAt: '2026-07-16' },
  },
  {
    slug: 'konya-mera-gozlem-gecesi',
    title: 'Karapınar Mera Gözlem Gecesi',
    type: 'gozlem-senligi',
    city: 'Konya',
    venue: 'Karapınar Meke Çevresi',
    coords: { latitude: 37.6833, longitude: 33.55 },
    startsAt: '2026-09-12T19:00:00+03:00',
    endsAt: '2026-09-13T04:00:00+03:00',
    free: true,
    camping: true,
    kidsFriendly: true,
    astrophotoFocused: true,
    telescopesProvided: true,
    organizer: { name: 'Konya Gökyüzü Gözlemcileri', verified: false },
    description:
      'İç Anadolu\'nun düz ufku ve kuru havası, geniş alan çekimleri için avantaj. Ay yeni ay evresinde; Samanyolu merkezi gece başında hâlâ yüksekte.',
    program: [
      { time: '19:00', title: 'Alan buluşması' },
      { time: '21:00', title: 'Samanyolu geniş açı çekim istasyonu' },
    ],
    observedTargets: ['Samanyolu', 'M 8', 'M 20', 'Satürn'],
    rules: ['Alan mera vasfındadır; çöp bırakılmaz, ateş yakılmaz.'],
    gradient: 'linear-gradient(135deg, #422006, #a16207)',
    source: { name: 'Topluluk paylaşımı', lastVerifiedAt: '2026-07-11' },
  },
  {
    slug: 'canakkale-tutulma-gozlemi',
    title: 'Parçalı Güneş Tutulması Gözlemi',
    type: 'gunes-gozlemi',
    city: 'Çanakkale',
    venue: 'Kilitbahir Sahil Parkı',
    coords: { latitude: 40.1442, longitude: 26.3789 },
    startsAt: '2026-08-12T11:00:00+03:00',
    endsAt: '2026-08-12T15:00:00+03:00',
    free: true,
    camping: false,
    kidsFriendly: true,
    astrophotoFocused: true,
    telescopesProvided: true,
    organizer: { name: 'Çanakkale Astronomi Topluluğu', verified: true },
    description:
      '12 Ağustos 2026 güneş tutulması Türkiye\'den parçalı izlenecek. Güvenli gözlem gözlükleri ve filtreli teleskoplar alanda dağıtılır.',
    program: [
      { time: '11:00', title: 'Güvenlik anlatımı ve gözlük dağıtımı' },
      { time: '12:30', title: 'Tutulma gözlemi ve projeksiyon' },
    ],
    observedTargets: ['Güneş'],
    rules: [
      'Filtresiz teleskop/dürbün kesinlikle kullanılmaz.',
      'Gözlük olmadan güneşe bakılmaz — kalıcı görme kaybı riski vardır.',
    ],
    gradient: 'linear-gradient(135deg, #7f1d1d, #f59e0b)',
    source: { name: 'Topluluk duyurusu', lastVerifiedAt: '2026-07-23' },
  },
];

export function getEventBySlug(slug: string): AstroEvent | undefined {
  return events.find((e) => e.slug === slug);
}
