import type { AstroEvent } from './types';

/** Etkinlik demo verisi — ana sayfa kartlarındaki slug'larla eşleşir. */
export const events: AstroEvent[] = [
  {
    slug: 'perseid-2026',
    title: 'Perseid Meteor Yağmuru Gözlem Kampı',
    type: 'meteor-yagmuru',
    city: 'Antalya',
    venue: 'Saklıkent Gözlem Alanı',
    startsAt: '2026-08-12T18:00:00+03:00',
    endsAt: '2026-08-13T06:00:00+03:00',
    free: false,
    camping: true,
    kidsFriendly: true,
    astrophotoFocused: true,
    telescopesProvided: true,
    capacity: 120,
    registered: 84,
    organizer: { name: 'Antalya Astronomi Derneği', verified: true },
    description:
      'Yılın en zengin meteor yağmurunu Bortle 3 gökyüzü altında izliyoruz. Zirve gecesi saatte 100+ meteor bekleniyor; çadır alanı, teleskop istasyonları ve astrofoto köşesi hazır olacak.',
    program: [
      { time: '18:00', title: 'Kamp kurulumu ve karşılama' },
      { time: '20:30', title: 'Perseidler nereden gelir?', speaker: 'Dr. A. Kaya' },
      { time: '22:00', title: 'Çıplak gözle gözlem ve sayım pratiği' },
      { time: '00:30', title: 'Teleskoplarla gezegen turu (Satürn, Jüpiter)' },
      { time: '04:30', title: 'Zirve saati toplu gözlem' },
    ],
    observedTargets: ['Perseid meteorları', 'Satürn', 'Jüpiter', 'Samanyolu'],
    rules: [
      'Beyaz ışık kullanımı 21:00 sonrası yasaktır; kırmızı fener getirin.',
      'Çadır alanı araçlara kapalıdır, otopark 200 m mesafededir.',
    ],
    gradient: 'linear-gradient(135deg, #1e293b, #4c1d95)',
    source: { name: 'Organizatör bildirimi', lastVerifiedAt: '2026-07-10' },
  },
  {
    slug: 'karanlik-gokyuzu',
    title: 'Karanlık Gökyüzü Astrofotoğraf Atölyesi',
    type: 'astrofoto-kampi',
    city: 'Erzurum',
    venue: 'Palandöken Yaylası',
    startsAt: '2026-08-20T16:00:00+03:00',
    endsAt: '2026-08-22T10:00:00+03:00',
    free: false,
    camping: true,
    kidsFriendly: false,
    astrophotoFocused: true,
    telescopesProvided: false,
    capacity: 30,
    registered: 27,
    organizer: { name: 'DeepSky Türkiye', verified: true },
    description:
      'İki gecelik uygulamalı atölye: kurulum, polar alignment, guiding, SHO veri toplama ve sabah oturumlarında işleme. Kendi ekipmanınızla katılım esastır; SQM 21.9 gökyüzü.',
    program: [
      { time: '1. Gün 16:00', title: 'Kurulum ve backfocus kontrolü' },
      { time: '1. Gün 21:00', title: 'Gece çekimi: Ha hedefleri' },
      { time: '2. Gün 10:00', title: 'WBPP ile kalibrasyon', speaker: 'D. Arslan' },
      { time: '2. Gün 21:00', title: 'Gece çekimi: OIII/SII' },
    ],
    observedTargets: ['NGC 7000', 'IC 1396', 'Sadr bölgesi'],
    gradient: 'linear-gradient(135deg, #0f172a, #7f1d1d)',
    source: { name: 'Organizatör bildirimi', lastVerifiedAt: '2026-07-08' },
  },
  {
    slug: 'halk-gozlemi',
    title: 'Halka Açık Teleskop Gözlemi',
    type: 'halk-gozlemi',
    city: 'İstanbul',
    venue: 'Maltepe Sahil Parkı',
    startsAt: '2026-08-28T20:00:00+03:00',
    free: true,
    camping: false,
    kidsFriendly: true,
    astrophotoFocused: false,
    telescopesProvided: true,
    organizer: { name: 'İstanbul Gökyüzü Gönüllüleri', verified: false },
    description:
      'Şehir merkezinde herkese açık gözlem akşamı. 6 teleskopla Ay kraterleri, Satürn halkaları ve çift yıldızlar. Kayıt gerekmez, çocuklar için kısa anlatım köşesi bulunur.',
    program: [
      { time: '20:00', title: 'Kurulum ve Ay gözlemi' },
      { time: '21:30', title: 'Satürn ve Jüpiter' },
      { time: '22:30', title: 'Çift yıldızlar ve kapanış' },
    ],
    observedTargets: ['Ay', 'Satürn', 'Jüpiter', 'Albireo'],
    gradient: 'linear-gradient(135deg, #1e3a5f, #334155)',
    source: { name: 'Kullanıcı önerisi + editör onayı', lastVerifiedAt: '2026-07-12' },
  },
  {
    slug: 'gunes-gozlemi-izmir',
    title: 'H-alfa ile Güneş Gözlemi',
    type: 'gunes-gozlemi',
    city: 'İzmir',
    venue: 'Kültürpark',
    startsAt: '2026-09-06T11:00:00+03:00',
    free: true,
    camping: false,
    kidsFriendly: true,
    astrophotoFocused: false,
    telescopesProvided: true,
    organizer: { name: 'Ege Üniversitesi Astronomi Kulübü', verified: true },
    description:
      'Özel H-alfa teleskoplarıyla güneş lekeleri ve protuberansları güvenle gözlemliyoruz. Güneşe asla çıplak gözle veya filtresiz teleskopla bakılmaz; tüm ekipman kulüp tarafından sağlanır.',
    program: [
      { time: '11:00', title: 'Güneş güvenliği anlatımı' },
      { time: '11:30', title: 'H-alfa ve beyaz ışık gözlemi' },
    ],
    observedTargets: ['Güneş lekeleri', 'Protuberanslar'],
    gradient: 'linear-gradient(135deg, #7c2d12, #b45309)',
    source: { name: 'Kulüp duyurusu', lastVerifiedAt: '2026-07-01' },
  },
  {
    slug: 'astronomi-101-webinar',
    title: 'Astronomiye Giriş: Ekipman Seçimi Webinarı',
    type: 'webinar',
    city: 'Online',
    venue: 'Canlı yayın',
    startsAt: '2026-07-30T21:00:00+03:00',
    free: true,
    camping: false,
    kidsFriendly: false,
    astrophotoFocused: true,
    telescopesProvided: false,
    organizer: { name: 'Astrohub Eğitim', verified: true },
    description:
      'İlk teleskop ve ilk astrofoto setup\'ı seçerken en sık yapılan hatalar; bütçe senaryolarıyla montür-öncelikli yaklaşım.',
    program: [{ time: '21:00', title: 'Sunum + soru/cevap', speaker: 'C. Demir' }],
    observedTargets: [],
    gradient: 'linear-gradient(135deg, #172554, #0e7490)',
    source: { name: 'Organizatör bildirimi', lastVerifiedAt: '2026-07-14' },
  },
];

export function getEventBySlug(slug: string): AstroEvent | undefined {
  return events.find((e) => e.slug === slug);
}
