-- Canlı kullanıcı ve dönemsel ülke/şehir raporu.
--
-- Ham IP saklanmaz. Edge Function IP'yi tuzlu hash'e ve maskeli ağa çevirir;
-- panel yalnızca ülke/şehir ve sayım kırılımını okur.

create table if not exists public.live_visitor_sessions (
  visitor_key text primary key,
  user_id uuid references auth.users(id) on delete set null,
  ip_hash text,
  ip_prefix text,
  country_code text,
  country_name text,
  region text,
  city text,
  timezone text,
  latitude numeric(9, 6),
  longitude numeric(9, 6),
  path text,
  user_agent_family text,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  seen_count integer not null default 1,
  updated_at timestamptz not null default now()
);

create index if not exists live_visitor_sessions_last_seen_idx
  on public.live_visitor_sessions (last_seen_at desc);
create index if not exists live_visitor_sessions_geo_idx
  on public.live_visitor_sessions (country_code, city, last_seen_at desc);

create table if not exists public.live_visitor_events (
  id bigint generated by default as identity primary key,
  visitor_key text not null,
  user_id uuid references auth.users(id) on delete set null,
  ip_hash text,
  ip_prefix text,
  country_code text,
  country_name text,
  region text,
  city text,
  timezone text,
  path text,
  seen_at timestamptz not null default now()
);

create index if not exists live_visitor_events_seen_idx
  on public.live_visitor_events (seen_at desc);
create index if not exists live_visitor_events_geo_idx
  on public.live_visitor_events (country_code, city, seen_at desc);
create index if not exists live_visitor_events_visitor_seen_idx
  on public.live_visitor_events (visitor_key, seen_at desc);

alter table public.live_visitor_sessions enable row level security;
alter table public.live_visitor_events enable row level security;

drop policy if exists live_visitor_sessions_admin_read on public.live_visitor_sessions;
create policy live_visitor_sessions_admin_read
on public.live_visitor_sessions
for select
to authenticated
using (app.is_admin());

drop policy if exists live_visitor_events_admin_read on public.live_visitor_events;
create policy live_visitor_events_admin_read
on public.live_visitor_events
for select
to authenticated
using (app.is_admin());

revoke all on public.live_visitor_sessions from anon, authenticated;
revoke all on public.live_visitor_events from anon, authenticated;
grant select on public.live_visitor_sessions to authenticated;
grant select on public.live_visitor_events to authenticated;

create or replace function public.record_live_visitor_session(
  p_visitor_key text,
  p_user_id uuid,
  p_ip_hash text,
  p_ip_prefix text,
  p_country_code text,
  p_country_name text,
  p_region text,
  p_city text,
  p_timezone text,
  p_latitude numeric,
  p_longitude numeric,
  p_path text,
  p_user_agent_family text,
  p_seen_at timestamptz
)
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.live_visitor_sessions (
    visitor_key, user_id, ip_hash, ip_prefix, country_code, country_name,
    region, city, timezone, latitude, longitude, path, user_agent_family,
    first_seen_at, last_seen_at, seen_count, updated_at
  )
  values (
    p_visitor_key, p_user_id, p_ip_hash, p_ip_prefix, p_country_code, p_country_name,
    p_region, p_city, p_timezone, p_latitude, p_longitude, p_path, p_user_agent_family,
    p_seen_at, p_seen_at, 1, p_seen_at
  )
  on conflict (visitor_key) do update
     set user_id = coalesce(excluded.user_id, public.live_visitor_sessions.user_id),
         ip_hash = excluded.ip_hash,
         ip_prefix = excluded.ip_prefix,
         country_code = excluded.country_code,
         country_name = excluded.country_name,
         region = excluded.region,
         city = excluded.city,
         timezone = excluded.timezone,
         latitude = excluded.latitude,
         longitude = excluded.longitude,
         path = excluded.path,
         user_agent_family = excluded.user_agent_family,
         last_seen_at = excluded.last_seen_at,
         seen_count = public.live_visitor_sessions.seen_count + 1,
         updated_at = excluded.updated_at;
$$;

comment on function public.record_live_visitor_session(
  text, uuid, text, text, text, text, text, text, text, numeric, numeric, text, text, timestamptz
) is 'Edge Function canlı ziyaretçi heartbeat kaydı. Ham IP kabul etmez.';

revoke all on function public.record_live_visitor_session(
  text, uuid, text, text, text, text, text, text, text, numeric, numeric, text, text, timestamptz
) from public;
grant execute on function public.record_live_visitor_session(
  text, uuid, text, text, text, text, text, text, text, numeric, numeric, text, text, timestamptz
) to service_role;

create or replace function public.admin_live_presence_report(
  p_from timestamptz default now() - interval '7 days',
  p_to timestamptz default now(),
  p_bucket text default 'day'
)
returns jsonb
language plpgsql
security definer
set search_path = public, app
as $$
declare
  aktif_esik timestamptz := now() - interval '2 minutes';
  bucket_interval text := case when p_bucket = 'hour' then 'hour' else 'day' end;
  sonuc jsonb;
begin
  if not app.is_admin() then
    raise exception 'Yönetici yetkisi gerekli.';
  end if;

  select jsonb_build_object(
    'generated_at', now(),
    'active_window_seconds', 120,
    'active_total', (
      select count(*)
      from public.live_visitor_sessions s
      where s.last_seen_at >= aktif_esik
    ),
    'active_locations', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'countryCode', country_code,
          'countryName', country_name,
          'region', region,
          'city', city,
          'label', label,
          'count', total
        )
        order by total desc, label
      )
      from (
        select
          coalesce(s.country_code, 'XX') as country_code,
          coalesce(s.country_name, 'Bilinmeyen ülke') as country_name,
          nullif(s.region, '') as region,
          nullif(s.city, '') as city,
          concat_ws(', ', nullif(s.city, ''), nullif(s.region, ''), coalesce(s.country_name, 'Bilinmeyen ülke')) as label,
          count(*) as total
        from public.live_visitor_sessions s
        where s.last_seen_at >= aktif_esik
        group by 1, 2, 3, 4, 5
      ) q
    ), '[]'::jsonb),
    'period', jsonb_build_object(
      'from', p_from,
      'to', p_to,
      'bucket', bucket_interval
    ),
    'period_total_events', (
      select count(*)
      from public.live_visitor_events e
      where e.seen_at >= p_from and e.seen_at < p_to
    ),
    'period_unique_visitors', (
      select count(distinct e.visitor_key)
      from public.live_visitor_events e
      where e.seen_at >= p_from and e.seen_at < p_to
    ),
    'top_locations', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'countryCode', country_code,
          'countryName', country_name,
          'region', region,
          'city', city,
          'label', label,
          'visitors', visitors,
          'events', events
        )
        order by visitors desc, events desc, label
      )
      from (
        select
          coalesce(e.country_code, 'XX') as country_code,
          coalesce(e.country_name, 'Bilinmeyen ülke') as country_name,
          nullif(e.region, '') as region,
          nullif(e.city, '') as city,
          concat_ws(', ', nullif(e.city, ''), nullif(e.region, ''), coalesce(e.country_name, 'Bilinmeyen ülke')) as label,
          count(distinct e.visitor_key) as visitors,
          count(*) as events
        from public.live_visitor_events e
        where e.seen_at >= p_from and e.seen_at < p_to
        group by 1, 2, 3, 4, 5
        order by visitors desc, events desc, label
        limit 20
      ) q
    ), '[]'::jsonb),
    'timeline', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'bucket', bucket_at,
          'visitors', visitors,
          'events', events
        )
        order by bucket_at
      )
      from (
        select
          date_trunc(bucket_interval, e.seen_at) as bucket_at,
          count(distinct e.visitor_key) as visitors,
          count(*) as events
        from public.live_visitor_events e
        where e.seen_at >= p_from and e.seen_at < p_to
        group by 1
      ) q
    ), '[]'::jsonb)
  )
  into sonuc;

  return sonuc;
end;
$$;

comment on function public.admin_live_presence_report(timestamptz, timestamptz, text) is
  'Admin canlı kullanıcı ve dönemsel ülke/şehir raporu. Ham IP döndürmez.';

revoke all on function public.admin_live_presence_report(timestamptz, timestamptz, text) from public;
grant execute on function public.admin_live_presence_report(timestamptz, timestamptz, text) to authenticated;
